apiVersion: v1
kind: Service
metadata:
  name: frontend-sw-service
spec:
  selector:
    app: api-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000